# Generated by Django 5.0.14 on 2026-07-16 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.academicperiod')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.level')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.academicperiod')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.level')),
            ],
            options={
                'unique_together': {('name', 'level', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='LecturerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicperiod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='courses.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lecturer', 'course', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='CourseRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rep_assignments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='courses.studentgroup')),
            ],
            options={
                'unique_together': {('student', 'group', 'academic_period')},
            },
        ),
    ]
