# Generated by Django 5.0.14 on 2026-07-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0002_alter_studentgroup_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courserep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courserep',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courserep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_course_reps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courserep',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='courserep',
            unique_together={('student', 'group', 'course', 'academic_period')},
        ),
    ]
